name: visily
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.0
  flutter_svg_provider: ^1.0.7
  responsive_grid_list: ^1.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Archivo
      fonts: 
        - asset: assets/fonts/ArchivoBold.ttf
          weight: 700
        - asset: assets/fonts/ArchivoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ArchivoMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
